
default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  username: postgres
  database: rails_demo_development


test:
  <<: *default
  username: postgres
  database: rails_demo_test


production:
  <<: *default
  database: rails_demo_production
  username: rails_demo
  password: <%= ENV['RAILS_DEMO_DATABASE_PASSWORD'] %>
